baseURL = "http://example.org/"
languageCode = "en-us"
title = "Duende IdentityServer Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
qs_base = "https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts/"